# Generated by Django 4.1.7 on 2024-07-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_student_course_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
