# Generated by Django 4.1.7 on 2024-07-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_remove_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporting',
        ),
    ]
